name: ola
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  uuid: ^4.1.0
  flutter_riverpod: ^2.4.5
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
